"""add form config to qr codes

Revision ID: 0c21138ba8aa
Revises: 38b6ac306124
Create Date: 2026-08-13 10:29:32.850650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c21138ba8aa'
down_revision: Union[str, Sequence[str], None] = '38b6ac306124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('form_config', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_codes', 'form_config')
    # ### end Alembic commands ###
