"""add qr customization fields

Revision ID: 38b6ac306124
Revises: c45688bd6cdb
Create Date: 2026-08-13 10:14:29.397612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38b6ac306124'
down_revision: Union[str, Sequence[str], None] = 'c45688bd6cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('campuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('campuses_code_key'), 'campuses', type_='unique')
    op.create_index(op.f('ix_campuses_campus_id'), 'campuses', ['campus_id'], unique=False)
    op.create_index(op.f('ix_campuses_code'), 'campuses', ['code'], unique=True)
    op.alter_column('gates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('gates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('gates_code_key'), 'gates', type_='unique')
    op.create_index(op.f('ix_gates_campus_id'), 'gates', ['campus_id'], unique=False)
    op.create_index(op.f('ix_gates_code'), 'gates', ['code'], unique=True)
    op.create_index(op.f('ix_gates_gate_id'), 'gates', ['gate_id'], unique=False)
    op.add_column('qr_codes', sa.Column('foreground_color', sa.String(length=7), nullable=False))
    op.add_column('qr_codes', sa.Column('background_color', sa.String(length=7), nullable=False))
    op.add_column('qr_codes', sa.Column('logo_enabled', sa.Boolean(), nullable=False))
    op.add_column('qr_codes', sa.Column('logo_reference', sa.String(length=100), nullable=True))
    op.add_column('qr_codes', sa.Column('size', sa.Integer(), nullable=False))
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('qr_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('qr_codes_code_key'), 'qr_codes', type_='unique')
    op.create_index(op.f('ix_qr_codes_code'), 'qr_codes', ['code'], unique=True)
    op.create_index(op.f('ix_qr_codes_gate_id'), 'qr_codes', ['gate_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_qr_code_id'), 'qr_codes', ['qr_code_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint(op.f('users_user_role_check'), 'users', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('users_user_role_check'), 'users', "user_role::text = ANY (ARRAY['admin'::character varying, 'security'::character varying, 'supervisor'::character varying, 'manager'::character varying]::text[])")
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_qr_codes_qr_code_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_gate_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_code'), table_name='qr_codes')
    op.create_unique_constraint(op.f('qr_codes_code_key'), 'qr_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('qr_codes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('qr_codes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('qr_codes', 'size')
    op.drop_column('qr_codes', 'logo_reference')
    op.drop_column('qr_codes', 'logo_enabled')
    op.drop_column('qr_codes', 'background_color')
    op.drop_column('qr_codes', 'foreground_color')
    op.drop_index(op.f('ix_gates_gate_id'), table_name='gates')
    op.drop_index(op.f('ix_gates_code'), table_name='gates')
    op.drop_index(op.f('ix_gates_campus_id'), table_name='gates')
    op.create_unique_constraint(op.f('gates_code_key'), 'gates', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('gates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gates', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_campuses_code'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_campus_id'), table_name='campuses')
    op.create_unique_constraint(op.f('campuses_code_key'), 'campuses', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('campuses', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('campuses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
