"""Sync all models

Revision ID: 5b29b69b597f
Revises: 0c21138ba8aa
Create Date: 2026-08-17 15:44:34.821219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b29b69b597f'
down_revision: Union[str, Sequence[str], None] = '0c21138ba8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_table('vehicles')
    op.drop_index(op.f('idx_dynamic_responses_form_id'), table_name='dynamic_responses')
    op.drop_index(op.f('idx_dynamic_responses_qr_code_id'), table_name='dynamic_responses')
    op.drop_table('dynamic_responses')
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('appointments_appointment_code_key'), 'appointments', type_='unique')
    op.drop_index(op.f('idx_appointments_code'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_created_by'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_date'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_status'), table_name='appointments')
    op.create_index(op.f('ix_appointments_appointment_code'), 'appointments', ['appointment_code'], unique=True)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.drop_constraint(op.f('appointments_checked_in_gate_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_campus_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_created_by_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_checked_in_security_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_visitor_record_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'visitors', ['visitor_record_id'], ['visitor_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'gates', ['checked_in_gate_id'], ['gate_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'campuses', ['campus_id'], ['campus_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'security', ['checked_in_security_id'], ['security_id'], ondelete='SET NULL')
    op.alter_column('dynamic_forms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('dynamic_forms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_index(op.f('idx_dynamic_forms_is_active'), table_name='dynamic_forms')
    op.create_index(op.f('ix_dynamic_forms_form_id'), 'dynamic_forms', ['form_id'], unique=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('qr_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_index(op.f('idx_qr_codes_form_id'), table_name='qr_codes')
    op.drop_index(op.f('idx_qr_codes_gate_id'), table_name='qr_codes')
    op.drop_constraint(op.f('qr_codes_code_key'), 'qr_codes', type_='unique')
    op.create_index(op.f('ix_qr_codes_code'), 'qr_codes', ['code'], unique=True)
    op.create_index(op.f('ix_qr_codes_form_id'), 'qr_codes', ['form_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_gate_id'), 'qr_codes', ['gate_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_qr_code_id'), 'qr_codes', ['qr_code_id'], unique=False)
    op.alter_column('scheduled_visits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('scheduled_visits_qr_pass_value_key'), 'scheduled_visits', type_='unique')
    op.create_index(op.f('ix_scheduled_visits_expected_date'), 'scheduled_visits', ['expected_date'], unique=False)
    op.create_index(op.f('ix_scheduled_visits_qr_pass_value'), 'scheduled_visits', ['qr_pass_value'], unique=True)
    op.create_index(op.f('ix_scheduled_visits_scheduled_visit_id'), 'scheduled_visits', ['scheduled_visit_id'], unique=False)
    op.alter_column('security', 'security_pin',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('security', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('security_security_pin_key'), 'security', type_='unique')
    op.create_index(op.f('ix_security_security_id'), 'security', ['security_id'], unique=False)
    op.alter_column('visitors', 'form_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('visitors', 'qr_code_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('visitors', 'gate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visitors', 'campus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_visitors_appointment_id'), 'visitors', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_visitors_checkout_security_id'), 'visitors', ['checkout_security_id'], unique=False)
    op.create_index(op.f('ix_visitors_form_id'), 'visitors', ['form_id'], unique=False)
    op.create_index(op.f('ix_visitors_gate_id'), 'visitors', ['gate_id'], unique=False)
    op.create_index(op.f('ix_visitors_qr_code_id'), 'visitors', ['qr_code_id'], unique=False)
    op.create_index(op.f('ix_visitors_security_id'), 'visitors', ['security_id'], unique=False)
    op.create_index(op.f('ix_visitors_visitor_id'), 'visitors', ['visitor_id'], unique=False)
    op.drop_constraint(op.f('visitors_appointment_id_fkey'), 'visitors', type_='foreignkey')
    op.drop_constraint(op.f('visitors_campus_id_fkey'), 'visitors', type_='foreignkey')
    op.create_foreign_key(None, 'visitors', 'campuses', ['campus_id'], ['campus_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'visitors', 'appointments', ['appointment_id'], ['appointment_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.create_foreign_key(op.f('visitors_campus_id_fkey'), 'visitors', 'campuses', ['campus_id'], ['campus_id'])
    op.create_foreign_key(op.f('visitors_appointment_id_fkey'), 'visitors', 'appointments', ['appointment_id'], ['appointment_id'])
    op.drop_index(op.f('ix_visitors_visitor_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_security_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_qr_code_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_gate_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_form_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_checkout_security_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_appointment_id'), table_name='visitors')
    op.alter_column('visitors', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('visitors', 'campus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visitors', 'gate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visitors', 'qr_code_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('visitors', 'form_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_security_security_id'), table_name='security')
    op.create_unique_constraint(op.f('security_security_pin_key'), 'security', ['security_pin'])
    op.alter_column('security', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('security', 'security_pin',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.drop_index(op.f('ix_scheduled_visits_scheduled_visit_id'), table_name='scheduled_visits')
    op.drop_index(op.f('ix_scheduled_visits_qr_pass_value'), table_name='scheduled_visits')
    op.drop_index(op.f('ix_scheduled_visits_expected_date'), table_name='scheduled_visits')
    op.create_unique_constraint(op.f('scheduled_visits_qr_pass_value_key'), 'scheduled_visits', ['qr_pass_value'])
    op.alter_column('scheduled_visits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_qr_codes_qr_code_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_gate_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_form_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_code'), table_name='qr_codes')
    op.create_unique_constraint(op.f('qr_codes_code_key'), 'qr_codes', ['code'])
    op.create_index(op.f('idx_qr_codes_gate_id'), 'qr_codes', ['gate_id'], unique=False)
    op.create_index(op.f('idx_qr_codes_form_id'), 'qr_codes', ['form_id'], unique=False)
    op.alter_column('qr_codes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('qr_codes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_index(op.f('ix_dynamic_forms_form_id'), table_name='dynamic_forms')
    op.create_index(op.f('idx_dynamic_forms_is_active'), 'dynamic_forms', ['is_active'], unique=False)
    op.alter_column('dynamic_forms', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('dynamic_forms', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_visitor_record_id_fkey'), 'appointments', 'visitors', ['visitor_record_id'], ['visitor_id'])
    op.create_foreign_key(op.f('appointments_checked_in_security_id_fkey'), 'appointments', 'security', ['checked_in_security_id'], ['security_id'])
    op.create_foreign_key(op.f('appointments_created_by_fkey'), 'appointments', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key(op.f('appointments_campus_id_fkey'), 'appointments', 'campuses', ['campus_id'], ['campus_id'])
    op.create_foreign_key(op.f('appointments_checked_in_gate_id_fkey'), 'appointments', 'gates', ['checked_in_gate_id'], ['gate_id'])
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_code'), table_name='appointments')
    op.create_index(op.f('idx_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('idx_appointments_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('idx_appointments_created_by'), 'appointments', ['created_by'], unique=False)
    op.create_index(op.f('idx_appointments_code'), 'appointments', ['appointment_code'], unique=False)
    op.create_unique_constraint(op.f('appointments_appointment_code_key'), 'appointments', ['appointment_code'])
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('dynamic_responses',
    sa.Column('response_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('qr_code_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('security_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_forms.form_id'], name=op.f('dynamic_responses_form_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.qr_code_id'], name=op.f('dynamic_responses_qr_code_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('dynamic_responses_security_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('response_id', name=op.f('dynamic_responses_pkey'))
    )
    op.create_index(op.f('idx_dynamic_responses_qr_code_id'), 'dynamic_responses', ['qr_code_id'], unique=False)
    op.create_index(op.f('idx_dynamic_responses_form_id'), 'dynamic_responses', ['form_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('qr_code_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('security_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('form_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checked_out_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checkout_security_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['checkout_security_id'], ['security.security_id'], name=op.f('vehicles_checkout_security_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_forms.form_id'], name=op.f('vehicles_form_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.gate_id'], name=op.f('vehicles_gate_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.qr_code_id'], name=op.f('vehicles_qr_code_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('vehicles_security_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('vehicle_id', name=op.f('vehicles_pkey'))
    )
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('qr_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('security_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('entries_pkey'))
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    # ### end Alembic commands ###
