"""Initial schema with users, campuses, gates, and qr_codes

Revision ID: c45688bd6cdb
Revises: 
Create Date: 2026-08-13 07:32:52.017096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45688bd6cdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('campus_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('campus_id')
    )
    op.create_index(op.f('ix_campuses_campus_id'), 'campuses', ['campus_id'], unique=False)
    op.create_index(op.f('ix_campuses_code'), 'campuses', ['code'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_pin', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('gates',
    sa.Column('gate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gate_id')
    )
    op.create_index(op.f('ix_gates_campus_id'), 'gates', ['campus_id'], unique=False)
    op.create_index(op.f('ix_gates_code'), 'gates', ['code'], unique=True)
    op.create_index(op.f('ix_gates_gate_id'), 'gates', ['gate_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('qr_code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.gate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qr_code_id')
    )
    op.create_index(op.f('ix_qr_codes_code'), 'qr_codes', ['code'], unique=True)
    op.create_index(op.f('ix_qr_codes_gate_id'), 'qr_codes', ['gate_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_qr_code_id'), 'qr_codes', ['qr_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_codes_qr_code_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_gate_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_code'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_gates_gate_id'), table_name='gates')
    op.drop_index(op.f('ix_gates_code'), table_name='gates')
    op.drop_index(op.f('ix_gates_campus_id'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_campuses_code'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_campus_id'), table_name='campuses')
    op.drop_table('campuses')
    # ### end Alembic commands ###
